# Generated by Django 5.1.5 on 2025-02-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetsForm',
            new_name='AssetsModel',
        ),
    ]
