# Generated by Django 5.1.5 on 2025-03-01 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0002_rename_assetsform_assetsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='corporate_floater',
            field=models.PositiveIntegerField(verbose_name='Корпоративные флоатеры'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='dividend_stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Дивидендные акции'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='gold',
            field=models.PositiveIntegerField(verbose_name='Золото'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='growth_stock',
            field=models.PositiveIntegerField(verbose_name='Акции роста'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='state_bond',
            field=models.PositiveIntegerField(verbose_name='ОФЗ'),
        ),
    ]
