# Generated by Django 5.1.5 on 2025-03-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0004_assetsmodel_total_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsmodel',
            name='total_i',
        ),
    ]
