# Generated by Django 5.1.5 on 2025-03-02 02:25

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0006_alter_assetsmodel_corporate_floater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsmodel',
            name='total_i',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gold'), '+', models.F('state_bond')), '+', models.F('corporate_floater')), '+', models.F('growth_stock')), '+', models.F('dividend_stock')), output_field=models.PositiveIntegerField()),
        ),
    ]
