# Generated by Django 5.1.5 on 2025-03-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0007_assetsmodel_total_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsmodel',
            name='total_i',
        ),
    ]
