# Generated by Django 5.1.5 on 2025-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0009_assetsmodel_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='interest_rate',
            field=models.FloatField(default=21.0, verbose_name='Процентная ставка'),
        ),
    ]
